import * as React from "react";
import * as Types from "./types";

declare function GuestbookComponentSlots(props: {
  as?: React.ElementType;
  componentComponentVisibility?: Types.Visibility.VisibilityConditions;
  componentComponentId?: Types.Basic.IdTextInput;
  guestbookMainHeadingGuestbookMainHeadingSlot?: Types.Devlink.Slot;
  leftContentBlockGuestbookSubHeadingSlot?: Types.Devlink.Slot;
  leftContentBlockGuestbookCountSlot?: Types.Devlink.Slot;
  rightContentBlockGuestbookFormSlot?: Types.Devlink.Slot;
  guestbookNameHeadingGuestbookNameHeadingSlot?: Types.Devlink.Slot;
  filterTagComponentFilterTagComponentSlot?: Types.Devlink.Slot;
  guestbookCard1GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard2GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard3GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard4GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard3RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard5GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard6GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard7GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard8GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard1RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard2RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard4RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard6RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard5RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard7RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard8RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard9GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard9RuntimeProps?: Types.Devlink.RuntimeProps;
  filterPreviousNextFilterPreviousNextSlotsSlot?: Types.Devlink.Slot;
  filterPreviousNextRuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookMainHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
  leftContentBlockGuestbookSubHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
  leftContentBlockGuestbookCountRuntimeProps?: Types.Devlink.RuntimeProps;
  rightContentBlockRuntimeProps?: Types.Devlink.RuntimeProps;
  filterTagComponentRuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookNameHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
