import * as React from "react";
import * as Types from "./types";

declare function GuestbookFilterTagsSlots(props: {
  as?: React.ElementType;
  componentRuntimeProps?: Types.Devlink.RuntimeProps;
  componentComponentId?: Types.Basic.IdTextInput;
  componentComponentVisibility?: Types.Visibility.VisibilityConditions;
  tag1NewestTagSlot?: Types.Devlink.Slot;
  tag1RuntimeProps?: Types.Devlink.RuntimeProps;
  tag2FamilyTagSlot?: Types.Devlink.Slot;
  tag2RuntimeProps?: Types.Devlink.RuntimeProps;
  tag3RelativeTagSlot?: Types.Devlink.Slot;
  tag3RuntimeProps?: Types.Devlink.RuntimeProps;
  tag4FriendsTagSlot?: Types.Devlink.Slot;
  tag4RuntimeProps?: Types.Devlink.RuntimeProps;
  tag4Visibility?: Types.Visibility.VisibilityConditions;
  tag5CoWorkerTagSlot?: Types.Devlink.Slot;
  tag6BusinessPartnerTagSlot?: Types.Devlink.Slot;
  tag5RuntimeProps?: Types.Devlink.RuntimeProps;
  tag5Visibility?: Types.Visibility.VisibilityConditions;
  tag6RuntimeProps?: Types.Devlink.RuntimeProps;
  tag1Visibility?: Types.Visibility.VisibilityConditions;
  tag2Visibility?: Types.Visibility.VisibilityConditions;
  tag3Visibility?: Types.Visibility.VisibilityConditions;
  tag6Visibility?: Types.Visibility.VisibilityConditions;
  tag7ChurchFriendSlot?: Types.Devlink.Slot;
  tag7RuntimeProps?: Types.Devlink.RuntimeProps;
  tag7Visibility?: Types.Visibility.VisibilityConditions;
  tag8NeverMetTagSlot?: Types.Devlink.Slot;
  tag8RuntimeProps?: Types.Devlink.RuntimeProps;
  tag8Visibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
