// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	ASSETS: Fetcher;
	SESSION: KVNamespace;
	WEBFLOW_CLOUD_MEDIA: R2Bucket;
	WEBFLOW_CMS_SITE_API_TOKEN?: string;
	WEBFLOW_CMS_SITE_API_WRITE_TOKEN?: string;
	WEBFLOW_API_HOST?: string;
}
