import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function MemoryJournalCardSlots(props: {
  card10CardId?: string;
  card10CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card10CardSlot?: Types.Devlink.Slot;
  card10CardVisibility?: Types.Visibility.VisibilityConditions;
  card11TallCardTallId?: string;
  card11TallCardTallRuntimeProps?: Types.Devlink.RuntimeProps;
  card11TallCardTallSlot?: Types.Devlink.Slot;
  card11TallCardTallVisibility?: Types.Visibility.VisibilityConditions;
  card1CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card1CardSlot?: Types.Devlink.Slot;
  card1CardSlotId?: string;
  card1CardVisibility?: Types.Visibility.VisibilityConditions;
  card2CardId?: string;
  card2CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card2CardSlot?: Types.Devlink.Slot;
  card2CardVisibility?: Types.Visibility.VisibilityConditions;
  card3WIdeCardRuntimeProps?: Types.Devlink.RuntimeProps;
  card3WIdeCardSlot?: Types.Devlink.Slot;
  card3WIdeCardSlotId?: string;
  card3WIdeCardSlotVisibility?: Types.Visibility.VisibilityConditions;
  card4CardId?: string;
  card4CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card4CardSlot?: Types.Devlink.Slot;
  card4CardVisibility?: Types.Visibility.VisibilityConditions;
  card5CardId?: string;
  card5CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card5CardSlot?: Types.Devlink.Slot;
  card5CardVisibility?: Types.Visibility.VisibilityConditions;
  card6TallCardTallId?: string;
  card6TallCardTallRuntimeProps?: Types.Devlink.RuntimeProps;
  card6TallCardTallSlot?: Types.Devlink.Slot;
  card6TallCardTallVisibility?: Types.Visibility.VisibilityConditions;
  card7CardId?: string;
  card7CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card7CardSlot?: Types.Devlink.Slot;
  card7CardVisibility?: Types.Visibility.VisibilityConditions;
  card8WIdeCardWIdeId?: string;
  card8WIdeCardWIdeRuntimeProps?: Types.Devlink.RuntimeProps;
  card8WIdeCardWIdeSlot?: Types.Devlink.Slot;
  card8WIdeCardWIdeVisibility?: Types.Visibility.VisibilityConditions;
  card9CardId?: string;
  card9CardRuntimeProps?: Types.Devlink.RuntimeProps;
  card9CardSlot?: Types.Devlink.Slot;
  card9CardVisibility?: Types.Visibility.VisibilityConditions;
  fIlterSlotsFIlterSlot?: Types.Devlink.Slot;
  fIlterSlotsFIlterSlotsId?: string;
  fIlterSlotsFIlterSlotsRuntimeProps?: Types.Devlink.RuntimeProps;
  fIlterSlotsFIlterSlotsVisibility?: Types.Visibility.VisibilityConditions;
  formButtonButtonId?: string;
  formButtonButtonRuntimeProps?: Types.Devlink.RuntimeProps;
  formButtonButtonSlot?: Types.Devlink.Slot;
  formButtonButtonVisibility?: Types.Visibility.VisibilityConditions;
  memoryJournalMainHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  memoryJournalMainParagraph?: React.ReactNode;
  memoryJournalMainParagraphVisibility?: Types.Visibility.VisibilityConditions;
  memoryJournalMemoryJournalMainHeadlineText?: React.ReactNode;
  memoryJournalSubHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  memoryJournalSubHeadlineText?: React.ReactNode;
}): React.JSX.Element;
