import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function GuestbookComponentSlots(props: {
  componentComponentId?: string;
  componentComponentVisibility?: Types.Visibility.VisibilityConditions;
  filterPreviousNextFilterPreviousNextSlotsSlot?: Types.Devlink.Slot;
  filterPreviousNextRuntimeProps?: Types.Devlink.RuntimeProps;
  filterTagComponentFilterTagComponentSlot?: Types.Devlink.Slot;
  filterTagComponentRuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard1GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard1RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard2GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard2RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard3GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard3RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard4GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard4RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard5GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard5RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard6GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard6RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard7GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard7RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard8GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard8RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookCard9GuestbookCardSlot?: Types.Devlink.Slot;
  guestbookCard9RuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookMainHeadingGuestbookMainHeadingSlot?: Types.Devlink.Slot;
  guestbookMainHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
  guestbookNameHeadingGuestbookNameHeadingSlot?: Types.Devlink.Slot;
  guestbookNameHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
  leftContentBlockGuestbookCountRuntimeProps?: Types.Devlink.RuntimeProps;
  leftContentBlockGuestbookCountSlot?: Types.Devlink.Slot;
  leftContentBlockGuestbookSubHeadingRuntimeProps?: Types.Devlink.RuntimeProps;
  leftContentBlockGuestbookSubHeadingSlot?: Types.Devlink.Slot;
  rightContentBlockGuestbookFormSlot?: Types.Devlink.Slot;
  rightContentBlockRuntimeProps?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
